### ISSUE TITLE
Can crash with uncaught exception without a gateway

### ISSUE THREAD

**Issue by XQANDAG** [mafintosh/multicast-dns#10]
Error: addMembership ENODEV
    at new errnoException (dgram.js:457:11)
    at Socket.addMembership (dgram.js:399:11)
    at Socket.<anonymous> (/home/blubb/node_modules/multicast-dns/index.js:46:16)

Occurs if I use the module without router / gateway. (Which isn't that problem, but the error is uncatchable. If you put the addMembership / socket part in a try / catch block and emit the error, it works fine.)

**Comment by mafintosh** [comment]
Feel free to send me a PR that adds that try-catch :)

**Comment by huanvu** [comment]
Submitted a PR for this, thanks in advance!

https://github.com/mafintosh/multicast-dns/pull/34
