### ISSUE TITLE
Should ANY be the default query type?

### ISSUE THREAD

**Issue by watson** [mafintosh/multicast-dns#15]
Today `A` is the default query type, e.g. `mdns.query('foo')` is equivalent to `mdns.query('foo', 'A')`. Wouldn't it make more sense that `ANY` was the default?

I'll happily make a PR if this is the case :smiley:

**Comment by mafintosh** [comment]
i'm ignorant. whats the difference?

**Comment by watson** [comment]
@mafintosh The `ANY` record is not a normal record type like `A`, `SRV` etc - it's only used when querying and functions as a wildcard question.

I would normally query for an `A` record to get only the ipv4 for the given hostname, eg `mdns.query('brunhilde.local', 'A')`. But if I want to get _all_ records for a given hostname I can issue an `ANY` query which basically means that mDNS servers should respond with _all_ the records they have for the given hostname (be it `A`, `AAAA`, `SRV`, `PTR` etc).

**Comment by watson** [comment]
More info: https://tools.ietf.org/html/rfc6762#section-6.5

**Comment by mafintosh** [comment]
Ah okay. Yea guess it makes sense then but we should document any records as supported then (and this would be a major bump)

**Comment by watson** [comment]
I'm not sure if this will require the module to officially **support** all record types. Just returning a response of type x isn't the same as adding query support for type x, right?

Today I can write `mdns.query('brunhilde.local', 'ANY')` and the module sends the correct query and hence responds with the expected responses as far as I can see - though maybe that's just a coincidence?
