### ISSUE TITLE
Support TXT data objects

### ISSUE THREAD

**Issue by watson** [mafintosh/multicast-dns#16]
When responding with a `TXT` record this module currently [expects the `data` property to be a string](https://github.com/mafintosh/multicast-dns/blob/6f876a5171ad5d4f9019f3aabcd5b11ffbadcd3f/packets.js#L131), e.g:

```js
mdns.respond([{
  name: 'foo',
  type: 'TXT',
  data: 'cn=0,1,2,3...'
}])
```

How about allowing it to be an object just as with the `SRV` record?

```js
mdns.respond([{
  name: 'foo',
  type: 'TXT',
  data: {
    cn: '0,1,2,3',
    model: 'AppleTV3,2'
  }
}])
```

**Comment by mafintosh** [comment]
Does the spec specify anything about formatting TXT records as querystrings? If not I'm :-1: since the response event would then still have to have the data be a string and then its kinda half baked

**Comment by watson** [comment]
@mafintosh I agree - Foolishly just assumed that it was so :stuck_out_tongue_winking_eye: So I just did a little digging:

RFC 6763 ("DNS-Based Service Discovery" or simply DNS-SD) have a section titled "[Data Syntax for DNS-SD TXT Records](https://tools.ietf.org/html/rfc6763#section-6)" which covers this.

DNS-SD is of cause just a subset of the mDNS standard and I don't know if all TXT records used within the mDNS universe have to adhere by this RFC, but if you read the [very beginning](https://tools.ietf.org/html/rfc6762#section-1) of the mDNS RFC (6762), it says:

> Multicast DNS and its companion technology DNS-Based Service
> Discovery [[RFC6763](https://tools.ietf.org/html/rfc6763)] were created to provide IP networking with the
> ease-of-use and autoconfiguration for which AppleTalk was well-known
> [[RFC6760](https://tools.ietf.org/html/rfc6760)].

So it seems like it should cover everything, but I'm not 100%
