### ISSUE TITLE
reuseAddr

### ISSUE THREAD

**Issue by xat** [mafintosh/multicast-dns#2]
On node v0.11.13 and above dgram.createSocket has a new option `reuseAddr` which is set to false by default (on prior versions it was true). This leads to the same problem like descriped here https://github.com/kmpm/node-mdns-js/issues/31

The problem could be solved with code like this:

```javascript
  if (semver.gte(process.versions.node, '0.11.13')) {
    socket = dgram.createSocket({type:'udp4', reuseAddr:true})
  } else {
    socket = dgram.createSocket('udp4')
  }
```

or like that:

```javascript
  if (typeof opts.reuseAddr !== 'undefined') {
    socket = dgram.createSocket({type:'udp4', reuseAddr:opts.reuseAddr})
  } else {
    socket = dgram.createSocket('udp4')
  }
```

Do you want a PR for one of those?

**Comment by mafintosh** [comment]
You already did pr and thanks! Fix released in 1.2.1

**Comment by xat** [comment]
I could have changed the PR if you wanted the other version :)

**Comment by xat** [comment]
thx!

**Comment by mafintosh** [comment]
Oh rigth. Do we need to set it to true for it to work on newer version of node/io ?

**Comment by xat** [comment]
you need to set it to true if you have some other mdns service running on your system which uses the same port, otherwise not. I guess often you will have to set that option.

**Comment by mafintosh** [comment]
@xat whats the downside of just defaulting it to true? :)

**Comment by xat** [comment]
Sounds like a good idea :) But then we will need the semver check.

**Comment by xat** [comment]
You mean like this?

```javascript
  if (typeof opts.reuseAddr === 'undefined') {
    opts.reuseAddr = true;
  }

  // ....

  if (semver.gte(process.versions.node, '0.11.13')) {
    socket = dgram.createSocket({type:'udp4', reuseAddr:opts.reuseAddr})
  } else {
    socket = dgram.createSocket('udp4')
  }
```

**Comment by mafintosh** [comment]
OR! we do this

``` js
var socket = dgram.createSocket({
  type: 'udp4',
  reuseAddr: opts.reuseAddr !== false,
  toString: function() { return opts.type }
})
```

too crazy?

**Comment by xat** [comment]
lol nice, but dosn't that return a string too on node >= v0.11.13 ?

**Comment by mafintosh** [comment]
Seems to work, https://github.com/joyent/node/blob/master/lib/dgram.js#L102-L105 (tested it locally as well)

**Comment by xat** [comment]
cool! :D

**Comment by mafintosh** [comment]
reuseAddr defaults to true in 2.0.0 now.

**Comment by xat** [comment]
+1
