### ISSUE TITLE
mDNS scan

### ISSUE THREAD

**Issue by fender357** [mafintosh/multicast-dns#23]
Hello, 
I have been trying to wrap my head around this since it seems like it should be something very simple.
I am basically trying to find a way to scan the network and find any mDNS client available. No matter what the name is of the client. 
What I believe DNS-SD would do in a way as well. I cannot find something that provides any name format that would work as a wild card. 

My goal would be to have something similar to the Bonjour browser program that can scan a network and find the client devices along with their IP

I feel like multicast-dns is very close to what I would need, I just don't know how to make it work like this.

Thank you

**Comment by fender357** [comment]
Hi there @watson , very interested in what you've got for this.

**Comment by watson** [comment]
@fender357 It's been a long time coming but I just released the [bonjour](https://github.com/watson/bonjour) node module which builds upon this module to provide a more high level interface for service discovery (and publishing).

As far as I know there are no way to scan for all bonjour/zeroconf clients without knowing the service-type they are advertising. I'd be happy to add this feature to [bonjour](https://github.com/watson/bonjour) if it was possible, but I don't think it is.

Please try out my new module if it can help you and don't hesitate to get back to me if you have any questions :smiley:

**Comment by fender357** [comment]
@watson Oh that's awesome :smiley: :+1: 

My understanding of mDNS has been slowly growing, and it has mostly been colored by my larger knowledge of multicast and IGMP. 
I keep expecting something like an IGMP Query message to be part of all this which will cause every possible participant to immediately come back with something.

Be I will definitely try your new module. I looked over it quickly and it looks really good!

I think I'll close this since there isn't technically any issue.
