### ISSUE TITLE
Add bin to resolve hostnames

### ISSUE THREAD

**Issue by techniq** [mafintosh/multicast-dns#4]
I find it very helpful on machines without multicast dns support (i.e Windows or Linux without Avahi installed) to use your library to resolve hostnames.  Currently I have a simple script to do this (as `mdns-resolve`):

```js
#!/usr/bin/env node

var mdns = require('multicast-dns')();

if (process.argv.length < 3) {
    console.log('Hostname required');
    process.exit(1);
}
var hostname = process.argv[2];

mdns.on('response', function(response) {
  response.answers.forEach(function(answer) {
    if (answer.name === hostname) {
        console.log(answer.data);
        process.exit();
    }
  });
});

mdns.query(hostname, 'A');

// Give responses 3 seconds to respond
setTimeout(function() {
    console.log('Hostname not found');
    process.exit();
}, 3000);
```

I was debating on creating a separate NPM package that uses this library, but I thought it might be worthwhile to add it here instead.  That way if someone installs using `npm install -g multicast-dns` the `cli/bin` script would be available.  I wanted your feedback on this before I decided which route to go (PR to add the feature here or create a separate NPM package).

I also wasn't sure how rich of a cli should be exposed (should just `A` records be looked up, or allow specifying others, etc.  I didn't want to add any dependencies like `yargs` for this unless the extra capabilities seemed worthwhile.  I was also between names for the program: `mdns-resolve`, `mdns-lookup`, `mdns-query`, or just expose `multicast-dns` as the name to match the library.

**Comment by mafintosh** [comment]
This sounds like a good idea to me. Could you send me a PR that add this to the module? I think we should call the cli `multicast-dns`. We can consider adding more *rich* features, like changing the record type, later
