### ISSUE TITLE
Get specific endpoint

### ISSUE THREAD

**Issue by zoecarver** [mafintosh/multicast-dns#54]
Is there any way to get an endpoint for the server? eg. response for `'/play'` would be different from `'/server-info'`?

**Comment by Bessonov** [comment]
That is not what dns is for. Use a reverse proxy like nginx.

**Comment by bnielsen1965** [comment]
@zoecarver  I am using the [DNS TXT Record](http://www.zeroconf.org/Rendezvous/txtrecords.html) for this purpose.

The purpose of this field is to provide additional information about a service.
