### ISSUE TITLE
How can I run mdns again after I do mdns.destroy();

### ISSUE THREAD

**Issue by kingeaglewang** [mafintosh/multicast-dns#59]
Hello,

After I run mdns.destroy();

I would like to re-run the mdns after a button click event.

How to re-run the mdns flow ?

Thank for helping.

**Comment by mafintosh** [comment]
You should make a new instance. .destroy completely destroys the instance.

**Comment by kingeaglewang** [comment]
I do as your README said.
mdns = multicastdns();

But it gets error
Uncaught ReferenceError: multicastdns is not defined
