### ISSUE TITLE
Service advertisement

### ISSUE THREAD

**Issue by techniq** [mafintosh/multicast-dns#6]
Is it possible to create a mdns advertisement similarly to how [node_mdns](https://github.com/agnat/node_mdns#synopsis) does, or is this simply a higher abstraction for something like `mdns.on('query', function(query) { ... })` that replies to specific questions of a type (`SRV`?)

**Comment by mafintosh** [comment]
yes you'd respond to the query event with a `response` message. see https://github.com/mafintosh/airpaste/blob/master/index.js#L29-L62 for an example. multicast-dns is a low-level impl of the mdns protocol. we should consider making a higher level module that wraps this to make it easier to use.

**Comment by techniq** [comment]
:+1: 

Is the service type (ex. `_http._tcp`) as mentioned on their [user guide](http://agnat.github.io/node_mdns/user_guide.html#service_types) get set as the [`name`](https://github.com/mafintosh/airpaste/blob/master/index.js#L45) or is that part of the [`data`](https://github.com/mafintosh/airpaste/blob/master/index.js#L46).

**Comment by mafintosh** [comment]
it's usually part of the `name` unless your record is a `PTR` record that points to another name

**Comment by techniq** [comment]
Thanks

**Comment by mafintosh** [comment]
Btw a module that would format the service types name, `formatMdns.http.tcp('test')` would probably be a good idea to write :)

**Comment by techniq** [comment]
Agreed ;)

**Comment by techniq** [comment]
https://github.com/agnat/node_mdns/blob/master/lib/service_type.js

**Comment by mafintosh** [comment]
I made this little thing now, https://github.com/mafintosh/multicast-dns-service-types

**Comment by techniq** [comment]
Awesome.  Thanks

**Comment by CMCDragonkai** [comment]
It would be great if you could update the README.md with the ability to use the `multicast-dns-service-types`.
