### ISSUE TITLE
allInterfaces - won't work with nodejs version 18.

### ISSUE THREAD

**Issue by erossignon** [mafintosh/multicast-dns#80]
in nodejs 18, os.networkInterfaces() now set familly to be either 4 or 6 instead of 'IPv6' || 'IPv4' 

![image](https://user-images.githubusercontent.com/680220/168389801-3fbc41a7-2c4e-4281-ab5a-b000278c719a.png)

As a consequence allInterfaces() method is failing.

```javascript

function allInterfaces () {
  var networks = os.networkInterfaces()
  var names = Object.keys(networks)
  var res = []

  for (var i = 0; i < names.length; i++) {
    var net = networks[names[i]]
    for (var j = 0; j < net.length; j++) {
      var iface = net[j]
      if (iface.family === 'IPv4') {
        res.push(iface.address)
        // could only addMembership once per interface (https://nodejs.org/api/dgram.html#dgram_socket_addmembership_multicastaddress_multicastinterface)
        break
      }
    }
  }

  return res
}
```

We need to replace

       if (iface.family === 'IPv4') 

with 

       if (iface.family === 'IPv4'  || iface.family === 4)

**Comment by erossignon** [comment]
see https://github.com/nodejs/node/issues/43014

**Comment by mafintosh** [comment]
fixed in master and latest release
