### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Digitum** [mafintosh/multicast-dns#84]
For a monitoring project, I need to get the source address from the ip packet. 
However, I can not find this in the queries and answers object. 

So, my suggestion is, if possible, to add source address and maybe even TTL to the object.

**Comment by mafintosh** [comment]
Its in the 2nd argument, rinfo to the events

**Comment by Digitum** [comment]
Ah, its even in the documentation, but not so obvious :-D
Thank you!

**Comment by mafintosh** [comment]
👍
